name: ui_kit
description: A new Flutter package project.
version: 0.0.1
homepage: "cd"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  infinite_scroll_pagination: ^3.2.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0
